apiVersion: v1
kind: Service
metadata:
  name: sfia2-service
spec:
  selector:
    app: myapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: nginx
        image: nginx
        ports: 
        - containerPort: 80
      - name: service1
        image: jasonsinclair95/sfia2:service1
        ports:
        - containerPort: 5000
      - name: service2
        image: jasonsinclair95/sfia2:service2
        ports:
        - containerPort: 5001
      - name: service3
        image: jasonsinclair95/sfia2:service3
        ports:
        - containerPort: 5002
      - name: service4
        image: jasonsinclair95/sfia2:service4
        ports:
        - containerPort: 5003