- name: install docker
  hosts: servers
  become: true
  roles:
    - install-docker

- name: add manager and intialise swarm
  hosts: manager-node
  become: true
  roles:
    - docker-swarm-init

- name: add workers nodes to the swarm
  hosts: worker-nodes
  become: true
  roles:
    - add-worker-nodes