- name: install docker
  hosts: servers
  become: true
  roles:
    - install-docker

- name: install docker localhost
  hosts: 127.0.0.1
  connection : local
  become: true
  roles:
    - install-docker

- name: add manager and intialise swarm
  hosts: 127.0.0.1
  connection: local
  become: true
  roles:
    - docker-swarm-init

- name: add workers nodes to the swarm
  hosts: worker-nodes
  become: true
  roles:
    - add-worker-nodes
  
